version: '3.4'
services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twitter
    volumes: 
      - mysql-data:/var/lib/mysql
  app:
    build: .
    image: app:1.0
    container_name: app
    ports:
      - 8000:8000
    depends_on: [mysql]
    environment:
      PASSWORD: password
      USERNAME: root
      HOST: mysql
      PORT: 3306
volumes:
    mysql-data:
        driver: local
